#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    positive = 0
    negative = 0
    zero = 0
    d = len(arr)
    for i in arr:
        if i > 0:
            positive += 1;
        elif i < 0:
            negative += 1;
        else: 
            zero += 1;
    print(positive/d)
    print(negative/d)
    print(zero/d)
        
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
