#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    n_spaces = n-1
    n_stairs = 1
    while n:
        print(" "*n_spaces + "#"*n_stairs)
        n -= 1
        n_spaces -= 1
        n_stairs += 1
        
if __name__ == '__main__':
    n = int(input())

    staircase(n)
