#!/bin/python3

import os
import sys
import datetime

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    #
    # Write your code here.
    #s_dt = datetime.datetime.strptime(t, '&I:%M:%S %p')
    #if s[:-2] = ("PM");
    a=''
    if s[-2:] == "AM" :
        if s[:2] == '12':
            a = str('00' + s[2:8])
        else:
             a = s[:-2]
    else:
        if s[:2] == '12':
            a = s[:-2]
        else:
             a = str(int(s[:2]) + 12) + s[2:8]
    return a

        
if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
